#!/usr/bin/env bash
# This script prints "Best School" 10 times using the while loop.

i="0"
while [ $i -lt 10 ]; do
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
    echo "Best School"
    i=$((i+1))
done