#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
# - display hours from 0 to 12
# - display minutes from 0 to 59

hours="0"
seconds="0"
while [ $hours -le 12 ]; do
    echo "Hour: $hours"
    while [ $seconds -le 59 ]; do
        echo "$seconds"
        seconds=$((seconds+1))
    done
    seconds="0"
    hours=$((hours+1))
done